"""empty message

Revision ID: 27dbb8cc81cb
Revises: bc54e93d0ead
Create Date: 2022-09-08 18:51:31.762335

"""
from alembic import op
import sqlalchemy as sa
from db.test_connections import TestBase


# revision identifiers, used by Alembic.
revision = '27dbb8cc81cb'
down_revision = 'bc54e93d0ead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
