"""Add category to quizz

Revision ID: 2c3c4edea2df
Revises: 85d6488eb07b
Create Date: 2022-09-20 16:22:26.499598

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '2c3c4edea2df'
down_revision = '85d6488eb07b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
