"""Add category to quizz

Revision ID: 2cd27c2f3a11
Revises: 5e3150f13b5d
Create Date: 2022-09-20 16:19:18.599006

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '2cd27c2f3a11'
down_revision = '5e3150f13b5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('quizz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'quizzes', ['quizz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'quizz_id')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
