"""Add category to quizz

Revision ID: 566ed751c87c
Revises: cd204a2e28f3
Create Date: 2022-09-20 15:07:20.273653

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '566ed751c87c'
down_revision = 'cd204a2e28f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('quizzes')
    # op.drop_constraint('questions_quizz_id_fkey', 'questions', type_='foreignkey')
    # op.drop_column('questions', 'quizz_id')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('quizz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_quizz_id_fkey', 'questions', 'quizzes', ['quizz_id'], ['id'])
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quizzes_pkey')
    )
    # ### end Alembic commands ###
