"""Back

Revision ID: 5a6b3964edff
Revises: 5d9e1087bccf
Create Date: 2022-09-20 18:41:44.242191

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '5a6b3964edff'
down_revision = '5d9e1087bccf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
