"""Add category to quizz

Revision ID: 5e3150f13b5d
Revises: 566ed751c87c
Create Date: 2022-09-20 16:18:24.774599

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '5e3150f13b5d'
down_revision = '566ed751c87c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'quizz_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('quizz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
