"""empty message

Revision ID: 697ae315d3fe
Revises: a0d42f7e1211
Create Date: 2022-09-08 19:06:32.396714

"""
from alembic import op
import sqlalchemy as sa
from db.test_connections import TestBase
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '697ae315d3fe'
down_revision = 'a0d42f7e1211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_quizz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('quizz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quizz_id'], ['test_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['test_categories.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_question_categories')
    op.drop_table('test_answers')
    op.drop_table('test_questions')
    op.drop_table('test_quizzes')
    op.drop_table('test_quizz_results')
    op.drop_table('test_categories')
    # ### end Alembic commands ###
