"""Add quizz_id column

Revision ID: 6f77ac294fbd
Revises: b29bf0c03adc
Create Date: 2022-09-21 12:11:33.360518

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '6f77ac294fbd'
down_revision = 'b29bf0c03adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('quizz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'quizzes', ['quizz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'quizz_id')
    # ### end Alembic commands ###
