"""Table corrections

Revision ID: 7b5a3eb2775c
Revises: 5a2687a9250a
Create Date: 2022-09-01 14:58:23.610384

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b5a3eb2775c'
down_revision = '5a2687a9250a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_results')
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('categories', 'desciption')
    op.add_column('questions', sa.Column('quizz_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_quiz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quizz_id'], ['id'])
    op.drop_column('questions', 'quiz_id')
    op.add_column('quizzes', sa.Column('description', sa.Text(),))
    op.alter_column('quizzes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('quizzes', 'desciption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('desciption', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('quizzes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('quizzes', 'description')
    op.add_column('questions', sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('questions', 'quizz_id')
    op.add_column('categories', sa.Column('desciption', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'description')
    op.create_table('quiz_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='quiz_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_results_pkey')
    )
    op.drop_table('quizz_results')
    # ### end Alembic commands ###
