"""Add category to quizz

Revision ID: 85d6488eb07b
Revises: 2cd27c2f3a11
Create Date: 2022-09-20 16:21:57.155475

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = '85d6488eb07b'
down_revision = '2cd27c2f3a11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
