"""empty message

Revision ID: a0d42f7e1211
Revises: e026a9b066b7
Create Date: 2022-09-08 18:59:18.235118

"""
from alembic import op
import sqlalchemy as sa
from db.test_connections import TestBase


# revision identifiers, used by Alembic.
revision = 'a0d42f7e1211'
down_revision = 'e026a9b066b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
