"""Table corrections2

Revision ID: ad5bd73d41ae
Revises: 7b5a3eb2775c
Create Date: 2022-09-01 15:18:16.024178

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = 'ad5bd73d41ae'
down_revision = '7b5a3eb2775c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.alter_column('quizzes', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('answers', 'is_correct')
    # ### end Alembic commands ###
