"""Back

Revision ID: b29bf0c03adc
Revises: 5a6b3964edff
Create Date: 2022-09-20 18:42:48.937817

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = 'b29bf0c03adc'
down_revision = '5a6b3964edff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
