"""empty message

Revision ID: bc54e93d0ead
Revises: 5ed7ebe1095b
Create Date: 2022-09-08 18:47:53.519346

"""
from alembic import op
import sqlalchemy as sa
from db.test_connections import TestBase


# revision identifiers, used by Alembic.
revision = 'bc54e93d0ead'
down_revision = '5ed7ebe1095b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
