"""Add category to quizz

Revision ID: cd204a2e28f3
Revises: 7b92cecc3826
Create Date: 2022-09-20 15:04:44.897206

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = 'cd204a2e28f3'
down_revision = '7b92cecc3826'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
