"""empty message

Revision ID: d8b1a7c0b009
Revises: 27dbb8cc81cb
Create Date: 2022-09-08 18:57:37.965659

"""
from alembic import op
import sqlalchemy as sa
from db.test_connections import TestBase


# revision identifiers, used by Alembic.
revision = 'd8b1a7c0b009'
down_revision = '27dbb8cc81cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
