"""empty message

Revision ID: e026a9b066b7
Revises: d8b1a7c0b009
Create Date: 2022-09-08 18:58:24.335039

"""
from alembic import op
import sqlalchemy as sa
from db.test_connections import TestBase


# revision identifiers, used by Alembic.
revision = 'e026a9b066b7'
down_revision = 'd8b1a7c0b009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
