"""empty message

Revision ID: f55d15ca45f7
Revises: ad5bd73d41ae
Create Date: 2022-09-02 19:41:42.825366

"""
from alembic import op
import sqlalchemy as sa
from db.connections import Base


# revision identifiers, used by Alembic.
revision = 'f55d15ca45f7'
down_revision = 'ad5bd73d41ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizz_results', sa.Column('user', sa.String(), nullable=True))
    op.drop_constraint('quizz_results_user_id_fkey', 'quizz_results', type_='foreignkey')
    op.drop_column('quizz_results', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizz_results', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('quizz_results_user_id_fkey', 'quizz_results', 'user', ['user_id'], ['id'])
    op.drop_column('quizz_results', 'user')
    # ### end Alembic commands ###
